---

version: "3.7"
services:
  scraper:
    build: ./alabama_scraper
    image: scraper:latest
    container_name: scraper
  prometheus:
    build: ./prometheus
    image: prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "prometheus-data:/etc/prometheus"
    container_name: prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      GF_INSTALL_PLUGINS: grafana-worldmap-panel
    container_name: grafana
      

volumes:
  grafana-data:
  prometheus-data:
