{
 "title": "COVID-19",
 "time": { "from": "2020-03-17T20:00:00.000Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "County", "query": "label_values(county_name)" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "content": "\n# Alabama COVID-19 Cases\n### Data automatically updated every hour\n[Department of Health Data Source](http://alabamapublichealth.gov/infectiousdiseases/2019-coronavirus.html) |\n[Source Code](https://github.com/chodges15/covid-county-growth) |\n[Samford's arcgis dashboard](https://samford.maps.arcgis.com/apps/webappviewer/index.html?id=5d07a1a339d841c2b1b72eeec2051781) |\n[MIT License](https://github.com/chodges15/covid-county-growth/blob/master/LICENSE) |\n[Nicer Looking Alabama Dashboard](https://alcovid19.info)\n"
  },
  {
   "title": "COVID-19 Case Trend",
   "type": "graph",
   "description": "Data source: http://alabamapublichealth.gov/infectiousdiseases/2019-coronavirus.html",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "case_count{job=\"covid\", county_name=~\"[[County]]\"} != 0",
     "legendFormat": "{{ county_name }}"
    }
   ]
  },
  {
   "title": "# New in Last 24H",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(case_count{job=\"covid\", county_name=~\"[[County]]\"}) - sum(case_count{job=\"covid\", county_name=~\"[[County]]\"} offset 1d)"
    }
   ]
  },
  {
   "title": "Counties Reporting Cases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "targets": [
    { "expr": "count(case_count != 0) / 67" }
   ]
  },
  {
   "title": "Alabama Statewide Cases",
   "type": "stat",
   "description": "Total number of confirmed cases statewide, ignores the county selection option above.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 19 },
   "targets": [
    { "expr": "sum(case_count)" }
   ]
  },
  {
   "title": "Statewide Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(case_count)", "legendFormat": "Cases" }
   ]
  },
  {
   "title": "Top Counties By Cases",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    { "expr": "topk(5, case_count)", "legendFormat": "{{county_name}}" }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "death_count{job=\"covid\", county_name=~\"[[County]]\"} != 0",
     "legendFormat": "{{ county_name }}"
    }
   ]
  }
 ]
}